### ISSUE TITLE
Don't require Error HPQTypesError

### ISSUE THREAD

**Issue by arybczak** [haskell-effectful/hpqtypes-effectful#27]
This is confusing since most of the functions from `hpqtypes` will throw HPQTypesError, but as a regular exception, which is different to the error handled by the `Error` effect (see https://hackage.haskell.org/package/effectful-core-1.1.0.0/docs/Effectful-Error-Static.html for more info).

I see that you've made GetConnectionStats use it, but it should just do what the original getConnectionStats implementation of DBT does.

**Comment by kawu** [comment]
>This is confusing since most of the functions from hpqtypes will throw HPQTypesError, but as a regular exception, which is different to the error handled by the Error effect (see https://hackage.haskell.org/package/effectful-core-1.1.0.0/docs/Effectful-Error-Static.html for more info).

Right, I see the problem now.

Something that crossed my mind before was to try to intercept HPQTypes exceptions and re-throw them as effectful errors, but maybe this doesn't make any sense?

By doing "what the original getConnectionStats implementation of DBT does" you mean simply using (or possibly re-implementing) [`throwDB`](https://hackage.haskell.org/package/hpqtypes-1.9.4.0/docs/Database-PostgreSQL-PQTypes-Utils.html#v:throwDB), right?  (if the approach from #25 is acceptable then it should be possible to just reuse it I think).

**Comment by arybczak** [comment]
> Something that crossed my mind before was to try to intercept HPQTypes exceptions and re-throw them as effectful errors, but maybe this doesn't make any sense?

It doesn't :slightly_smiling_face: These functions can also throw `LibPQError` and `DBException` and keeping track of these would be a PITA.
